GENERATED_FILE_HEADERS = [
    'Sku',
    'Fnsku',
    'Asin',
    'Product - name',
    'Condition',
    'Your - price',
    'Mfn - listing - exists',
    'mfn - fulfillable - quantity',
    'Afn - listing - exists',
    'Afn - warehouse - quantity',
    'Afn - fulfillable - quantity',
    'Afn - unsellable - quantity',
    'Afn - reserved - quantity',
    'Afn - total - quantity',
    'Per - unit - volume',
    'Afn - inbound - working - quantity',
    'Afn - inbound - shipped - quantity',
    'Afn - inbound - receiving - quantity',
    'Afn - researching - quantity',
    'Afn - reserved - future - supply',
    'Afn - future - supply - buyable',
    'Reserved_qty',
    'Reserved_customerorders',
    'Reserved_fc - transfers',
    'Reserved_fc - processing',
    'Cfn - warehouse - quantity',
    'Cfn - fulfillable - quantity',
    'Cfn - unsellable - quantity',
    'Cfn - reserved - quantity',
    'Cfn - total - quantity']
